# Generated by Django 4.2.8 on 2024-01-14 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_room_current_song"),
        ("spotify", "0003_votes"),
    ]

    operations = [
        migrations.RenameModel(old_name="Votes", new_name="Vote",),
    ]
